MOD_UCRYPTOGRAPHY_DIR := $(USERMOD_DIR)

SRC_USERMOD += $(MOD_UCRYPTOGRAPHY_DIR)/modcryptography.c

CFLAGS_USERMOD += -I$(MOD_UCRYPTOGRAPHY_DIR)
CFLAGS_USERMOD += -I$(MOD_UCRYPTOGRAPHY_DIR)/mbed-crypto/include

CFLAGS_USERMOD += -DMICROPY_PY_UCRYPTOGRAPHY=1
CFLAGS_USERMOD += -DMICROPY_PY_UCRYPTOGRAPHY_VERSION=1